name: Docker Image CI

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to the Container registry
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

#         - name: Extract metadata (tags, labels) for Docker
#           id: meta
#           uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#           with:
#             images: ${{ env.REGISTRY }}/${{ env.IMAGE }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            push: true
            context: .
            file: ./Dockerfile
            tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
