name: deploy to ec2

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  Deploy:
    name: ssh to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SERVER_IP}}
            USER_NAME: ${{secrets.DEPLOY_USER}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
            touch fuck_you
